# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'export-solution'
description: 'Power Platform Export Solution'
inputs:
  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: true

  user-name:
    description: 'Power Platform user name to authenticate with, e.g. myname@my-org.onmicrosoft.com. Setting this input makes user-name and password required; specifying alternate "app-id" credential set of inputs will result in an error.'
    required: false

  password-secret:
    description: 'Power Platform password, required if authenticating with username. Do NOT checkin password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: false

  app-id:
    description: 'The application id to authenticate with. Setting this input makes app-id, tenant-id and client-secret required; specifying alternate "username" credential set of inputs will result in an error.'
    required: false

  client-secret:
    description: 'The client secret to authenticate with. Required if authenticating with app-id.'
    required: false

  tenant-id:
    description: 'Tenant id if using app-id & client secret to authenticate.'
    required: false

  solution-name:
    description: 'Name of solution to export'
    required: true

  solution-version:
    description: 'Version of solution to export'
    required: false

  solution-output-file:
    description: 'Path/filename where to place the exported solution zip file. Can be absolute or relative to working-directory'
    required: true

  managed:
    description: 'Export as managed solution; default is to export as unmanaged solution'
    required: false

  working-directory:
    description: 'Working directory; default: root of repository'
    required: false

  run-asynchronously:
    description: 'Exports solution asynchronously'
    required: false

runs:
  using: 'node12'
  main: '../dist/actions/export-solution/index.js'
  # main: '../out/actions/export-solution/index.js'
